<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkillOfferSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
{
    \App\Models\SkillOffer::insert([
        [
            'name' => 'John Smith',
            'skill_name' => 'Python Programming',
            'skill_level' => 'Intermediate',
            'session_type' => 'Online',
            'contact_method' => 'email@example.com',
            'availability_notes' => 'Evenings after 6 PM',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Aisha Khan',
            'skill_name' => 'Graphic Design',
            'skill_level' => 'Beginner',
            'session_type' => 'In-person',
            'contact_method' => 'phone: 07324 555321',
            'availability_notes' => 'Weekends only',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Michael Lee',
            'skill_name' => 'JavaScript',
            'skill_level' => 'Advanced',
            'session_type' => 'Online',
            'contact_method' => 'michael@example.com',
            'availability_notes' => '',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Sophia Patel',
            'skill_name' => 'Singing',
            'skill_level' => 'Intermediate',
            'session_type' => 'In-person',
            'contact_method' => 'sophia@gmail.com',
            'availability_notes' => 'Only weekdays',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Daniel Green',
            'skill_name' => 'Cooking (Italian)',
            'skill_level' => 'Advanced',
            'session_type' => 'In-person',
            'contact_method' => 'daniel123@example.com',
            'availability_notes' => '',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Emma Johnson',
            'skill_name' => 'Photography',
            'skill_level' => 'Beginner',
            'session_type' => 'Online',
            'contact_method' => 'emma@example.com',
            'availability_notes' => 'After 5pm',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Kevin Brown',
            'skill_name' => 'Guitar',
            'skill_level' => 'Intermediate',
            'session_type' => 'In-person',
            'contact_method' => 'contact@kevin.com',
            'availability_notes' => 'Flexible timing',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Laura Wilson',
            'skill_name' => 'English Tutoring',
            'skill_level' => 'Advanced',
            'session_type' => 'Online',
            'contact_method' => 'laura@example.com',
            'availability_notes' => '',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        // ---- Continue adding more entries until 30 ---- //

        [
            'name' => 'Chris Walker',
            'skill_name' => 'Video Editing',
            'skill_level' => 'Intermediate',
            'session_type' => 'Online',
            'contact_method' => 'chris@example.com',
            'availability_notes' => 'Evenings',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Nadia Hussain',
            'skill_name' => 'Baking',
            'skill_level' => 'Beginner',
            'session_type' => 'In-person',
            'contact_method' => 'nadia@gmail.com',
            'availability_notes' => '',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Liam Carter',
            'skill_name' => 'Public Speaking',
            'skill_level' => 'Advanced',
            'session_type' => 'Online',
            'contact_method' => 'liam@example.com',
            'availability_notes' => 'Weekends only',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Isabella Martin',
            'skill_name' => 'Painting',
            'skill_level' => 'Intermediate',
            'session_type' => 'In-person',
            'contact_method' => 'bella@example.com',
            'availability_notes' => '',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Oliver Scott',
            'skill_name' => 'Mathematics Tutoring',
            'skill_level' => 'Advanced',
            'session_type' => 'Online',
            'contact_method' => 'oliver@example.com',
            'availability_notes' => 'Only mornings',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        // Continue until 30 records...
        // I'll add enough to complete the list:

        [
            'name' => 'Ava Thompson',
            'skill_name' => 'French Language',
            'skill_level' => 'Intermediate',
            'session_type' => 'Online',
            'contact_method' => 'ava@example.com',
            'availability_notes' => '',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Ethan Moore',
            'skill_name' => 'Chess Coaching',
            'skill_level' => 'Advanced',
            'session_type' => 'In-person',
            'contact_method' => 'ethan@example.com',
            'availability_notes' => 'After 6pm',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Mia Brooks',
            'skill_name' => 'Yoga',
            'skill_level' => 'Beginner',
            'session_type' => 'In-person',
            'contact_method' => 'miab@example.com',
            'availability_notes' => '',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Noah Perez',
            'skill_name' => 'Carpentry',
            'skill_level' => 'Intermediate',
            'session_type' => 'In-person',
            'contact_method' => 'noah@example.com',
            'availability_notes' => 'Weekdays only',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Chloe Adams',
            'skill_name' => 'Sewing',
            'skill_level' => 'Beginner',
            'session_type' => 'Online',
            'contact_method' => 'chloe@example.com',
            'availability_notes' => 'Flexible',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Lucas Evans',
            'skill_name' => 'Coding (Java)',
            'skill_level' => 'Intermediate',
            'session_type' => 'Online',
            'contact_method' => 'lucas@example.com',
            'availability_notes' => '',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Harper Simmons',
            'skill_name' => 'Dancing',
            'skill_level' => 'Advanced',
            'session_type' => 'In-person',
            'contact_method' => 'harper@example.com',
            'availability_notes' => 'Only weekends',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        // Add more to reach 30...
        [
            'name' => 'Grace Mitchell',
            'skill_name' => 'Knitting',
            'skill_level' => 'Beginner',
            'session_type' => 'Online',
            'contact_method' => 'grace@example.com',
            'availability_notes' => '',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Henry Collins',
            'skill_name' => 'Football Coaching',
            'skill_level' => 'Intermediate',
            'session_type' => 'In-person',
            'contact_method' => 'henry@example.com',
            'availability_notes' => 'Evenings',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Ella Turner',
            'skill_name' => 'Makeup Artistry',
            'skill_level' => 'Advanced',
            'session_type' => 'In-person',
            'contact_method' => 'ella@example.com',
            'availability_notes' => 'Morning sessions',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Jack Kelly',
            'skill_name' => 'Android Development',
            'skill_level' => 'Intermediate',
            'session_type' => 'Online',
            'contact_method' => 'jack@example.com',
            'availability_notes' => '',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Lily Foster',
            'skill_name' => 'Ballet',
            'skill_level' => 'Beginner',
            'session_type' => 'In-person',
            'contact_method' => 'lily@example.com',
            'availability_notes' => '',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Samuel Price',
            'skill_name' => 'Web Design',
            'skill_level' => 'Intermediate',
            'session_type' => 'Online',
            'contact_method' => 'samuel@example.com',
            'availability_notes' => 'After 7pm',
            'created_at' => now(),
            'updated_at' => now(),
        ],
    ]);
}


}
